---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python-pip' , 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull Springboot
      docker_image:
        name: "yativg/spring"
        source: pull

    - name: Pull nginx
      docker_image:
        name: "nginx"
        source: pull

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: ansible create directory example
      file:
        path: /tmp/Skai
        state: directory
    
    - name: Clone a github repository
      git:
        repo: https://github.com/Yativg/SKAIProject.git
        dest: /tmp/Skai/
        clone: yes

    - name: Run
      become: True
      shell:
        cmd: "docker-compose up -d"
        chdir: /tmp/Skai
