Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network", ip: "192.168.1.1"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook       = "skai.yaml"
    ansible.verbose        = true
    ansible.install        = true
    ansible.limit          = "all" # or only "nodes" group, etc.
 end
end
